---
apiVersion: v1
kind: Pod
metadata:
    name: httpd-pod
    labels:
        kwas-label: httpd-label
spec:
    containers:
      - name: httpd-container
        image: httpd
        ports:
          - name: http-port
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: httpd-service
spec:
    ports:
      - name: http
        port: 80
        nodePort: 30080
    selector:
        kwas-label: httpd-label
    type: NodePort
