apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/secrets/ca.pem
    server: https://kube-master:6443
  name: kube-cluster
contexts:
- context:
    cluster: kube-cluster
    user: coredns
  name: coredns
current-context: coredns
kind: Config
preferences: {}
users:
- name: coredns
  user:
    client-certificate: /etc/secrets/coredns.pem
    client-key: /etc/secrets/coredns.key
