apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://kube-master:8080
  name: master
contexts:
- context:
    cluster: master
    user: ""
  name: master
current-context: master
kind: Config
preferences: {}
users: []
