apiVersion: v1
clusters:
- cluster:
    server: https://kube-master:6443
  name: master
contexts:
- context:
    cluster: master
    user: ""
  name: master
current-context: master
kind: Config
preferences: {}
users: []
