apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/secrets/ca.pem
    server: https://kube-master:6443
  name: kube-cluster
contexts:
- context:
    cluster: kube-cluster
    user: kube-user
  name: master
current-context: master
kind: Config
preferences: {}
users:
- name: kube-user
  user:
    client-certificate: /etc/secrets/host.pem
    client-key: /etc/secrets/host.key
