---
ingress:
  enabled: true

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 0

  hosts:
  - registry.kube-ingress.local

  tls:
  - secretName: wildcard-ingress-secret
    hosts:
    - registry.kube-ingress.local
